tests n.2.11

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -69,30 +69,30 @@ jobs:
             echo "Create databases..."
             docker-compose run create_dbs
 
+            echo "Migrate woken database..."
+            docker-compose run woken_db_setup
+
+            echo "Migrate metadata database..."
+            docker-compose run meta_db_setup
+
+            echo "Migrate features database..."
+            docker-compose run sample_data_db_setup
+
+            echo "Run containers..."
+            for i in 1 2 3 4 5 ; do
+              docker-compose up -d chronos
+              docker-compose run wait_chronos
+              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
+              echo "Chronos failed to start, restarting..."
+              docker-compose stop chronos
+            done
+
+            docker-compose up -d woken wokenvalidation
+
+            docker-compose run wait_woken
+
             docker images -a
             docker ps -a
-
-#            echo "Migrate woken database..."
-#            docker-compose run woken_db_setup
-#
-#            echo "Migrate metadata database..."
-#            docker-compose run meta_db_setup
-#
-#            echo "Migrate features database..."
-#            docker-compose run sample_data_db_setup
-#
-#            echo "Run containers..."
-#            for i in 1 2 3 4 5 ; do
-#              docker-compose up -d chronos
-#              docker-compose run wait_chronos
-#              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
-#              echo "Chronos failed to start, restarting..."
-#              docker-compose stop chronos
-#            done
-#
-#            docker-compose up -d woken wokenvalidation
-#
-#            docker-compose run wait_woken
 #
 #            for i in 1 2 3 4 5 ; do
 #              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
