tests n.2.8

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -43,51 +43,55 @@ jobs:
             git clone https://github.com/LREN-CHUV/web-analytics-starter.git
             cd web-analytics-starter
             docker --version
+            groups "$USER" | grep &>/dev/null
 
-            echo "Deploy a Postgres server and wait for it to be ready..."
-            docker-compose up -d db zookeeper
-            docker-compose run wait_zookeeper
-            docker-compose up -d mesos_master
-            docker-compose run wait_mesos_master
-            docker-compose up -d mesos_slave
-            docker-compose run wait_dbs
+#            echo "Deploy a Postgres server and wait for it to be ready..."
+#            docker-compose up -d db zookeeper
+#            docker-compose run wait_zookeeper
+#            docker-compose up -d mesos_master
+#            docker-compose run wait_mesos_master
+#            docker-compose up -d mesos_slave
+#            docker-compose run wait_dbs
+#
+#            echo "Create databases..."
+#            docker-compose run create_dbs
+#
+#            echo "Migrate woken database..."
+#            docker-compose run woken_db_setup
+#
+#            echo "Migrate metadata database..."
+#            docker-compose run meta_db_setup
+#
+#            echo "Migrate features database..."
+#            docker-compose run sample_data_db_setup
+#
+#            echo "Run containers..."
+#            for i in 1 2 3 4 5 ; do
+#              docker-compose up -d chronos
+#              docker-compose run wait_chronos
+#              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
+#              echo "Chronos failed to start, restarting..."
+#              docker-compose stop chronos
+#            done
+#
+#            docker-compose up -d woken wokenvalidation
+#
+#            docker-compose run wait_woken
+#
+#            for i in 1 2 3 4 5 ; do
+#              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
+#              echo "Chronos failed to start, restarting..."
+#              docker-compose stop chronos
+#              docker-compose up -d chronos
+#              docker-compose run wait_chronos
+#            done
+#
+#            docker-compose up -d backend
+#            docker-compose run wait_portal_backend
+#            docker-compose up -d frontend
 
-            echo "Create databases..."
-            docker-compose run create_dbs
 
-            echo "Migrate woken database..."
-            docker-compose run woken_db_setup
 
-            echo "Migrate metadata database..."
-            docker-compose run meta_db_setup
-
-            echo "Migrate features database..."
-            docker-compose run sample_data_db_setup
-
-            echo "Run containers..."
-            for i in 1 2 3 4 5 ; do
-              docker-compose up -d chronos
-              docker-compose run wait_chronos
-              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
-              echo "Chronos failed to start, restarting..."
-              docker-compose stop chronos
-            done
-
-            docker-compose up -d woken wokenvalidation
-
-            docker-compose run wait_woken
-
-            for i in 1 2 3 4 5 ; do
-              docker-compose logs chronos | grep java.util.concurrent.TimeoutException || break
-              echo "Chronos failed to start, restarting..."
-              docker-compose stop chronos
-              docker-compose up -d chronos
-              docker-compose run wait_chronos
-            done
-
-            docker-compose up -d backend
-            docker-compose run wait_portal_backend
-            docker-compose up -d frontend
 #            sudo ./run.sh
 #      - run:
 #          name: "Build the project"
